name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: ['22.18.0', '24']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: git config --global core.autocrlf input
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm run typecheck
      - run: npm test
